sudo: false
language: rust
rust:
- 1.22.0  # Two releases back
- stable
- beta
- nightly
matrix:
  include:
  - env: RUSTFMT
    rust: 1.25.0  # `stable`: Locking down for consistent behavior
    install:
      - rustup component add rustfmt-preview
    script:
      - cargo fmt -- --write-mode=diff
  - env: RUSTFLAGS="-D warnings"
    rust: 1.25.0  # `stable`: Locking down for consistent behavior
    install:
    script:
    - cargo check --tests --all-features
  - env: CLIPPY_VERSION="0.0.179"
    rust: nightly-2018-01-12
    install:
      - travis_wait cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
    script:
      - cargo clippy --all-features -- -D clippy

install:
- rustc -Vv
- cargo -V
- export PATH=$HOME/.cargo/bin:$PATH

script:
- cargo check --verbose
- cargo check --verbose --no-default-features
- cargo check --verbose --all-features
- cargo test  --verbose --all-features

branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

cache:
  apt: true
  cargo: true
before_cache:
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
